services:
  - type: web
    name: jyotiflow-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /health

  - type: web
    name: jyotiflow-ai-frontend
    env: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_URL
        value: https://jyotiflow-ai.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


